export const VITAL_TYPES = [
  { label: "Heart Rate", code: "8867-4", unit: "/min" },
  { label: "Respiratory Rate", code: "9279-1", unit: "/min" },
  { label: "Oxygen Saturation", code: "2708-6", unit: "%" },
  { label: "Body Temperature", code: "8310-5", unit: "Cel" },
  { label: "Body Height", code: "8302-2", unit: "cm" },
  { label: "Body Weight", code: "29463-7", unit: "kg" },
  { label: "Body Mass Index", code: "39156-5", unit: "kg/m2" },
  { label: "Head Circumference", code: "9843-4", unit: "cm" },
  { label: "Blood Pressure", code: "85354-9", unit: "mm[Hg]" },
];
export const EMPTY_FORMS = {
  Condition: { display: "", status: "active", onsetDate: "" },
  MedicationRequest: {
    medication: "",
    dosage: "",
    frequency: "",
    status: "active",
    date: "",
  },
  AllergyIntolerance: {
    display: "",
    substance: "",
    type: "allergy",
    category: "medication",
    criticality: "low",
    status: "active",
    date: "",
  },
  Observation: {
    display: "",
    vitalType: "Blood Pressure",
    value: "",
    unit: "",
    system: "",
    date: "",
  },
  Immunization: { vaccine: "", date: "", status: "completed" },
  MedicationStatement: {
    medication: "",
    status: "active",
    statusReason: "",
    category: "outpatient",
    effectiveDate: "",
    dateAsserted: "",
    reasonCode: "",
    dosage: "",
    notes: "",
  },
  Procedure: {
    display: "",
    status: "completed",
    statusReason: "",
    category: "",
    performedDate: "",
    performer: "",
    location: "",
    reasonCode: "",
    bodySite: "",
    outcome: "",
    notes: "",
  },
  DiagnosticReport: {
    display: "",
    status: "final",
    category: "",
    effectiveDate: "",
    issued: "",
    performer: "",
    resultsInterpreter: "",
    result: "",
    conclusion: "",
    conclusionCode: "",
  },
  Flag: {
    display: "",
    status: "active",
    category: "",
    periodStart: "",
    periodEnd: "",
    author: "",
    encounter: "",
    notes: "",
  },
  CarePlan: {
    title: "",
    description: "",
    status: "active",
    intent: "plan",
    category: "",
    periodStart: "",
    periodEnd: "",
    author: "",
    addresses: "",
    activity: "",
    notes: "",
  },
  FamilyMemberHistory: {
    name: "",
    relationship: "MTH",
    status: "completed",
    sex: "unknown",
    bornDate: "",
    age: "",
    deceasedBoolean: false,
    deceasedDate: "",
    condition: "",
    reasonCode: "",
    notes: "",
    date: "",
  },
};